#!/bin/sh
# /etc/init.d/startup

# mount the special pseudo filesytems /proc and /sys
mount -t proc proc /proc -o nosuid,noexec,nodev
mount -t sysfs sys /sys -o nosuid,noexec,nodev

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# NOTE: This was causing issues indeed, but it does seem to be optional
# though it would probably break if we implemented initramfs

# /dev isn't required if we boot without initramfs because the kernel
# will have done this for us but it doesn't hurt
# mount -t devtmpfs dev /dev -o mode=0755,nosuid
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

mkdir -p /dev/pts /dev/shm
# /dev/pts contains pseudo-terminals, gid 5 should be the
# tty user group
mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec

# /run contains runtime files like pid files and domain sockets
# they don't need to be stored on the disk, we'll store them in RAM
mount -t tmpfs run /run -o mode=0755,nosuid,nodev
mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev
# the nosuid,noexec,nodev options are for security reasons and are not
# strictly necessary, you can read about them in the 'mount'
# man page

# the kernel does not read /etc/hostname on it's own
# you need to write it in /proc/sys/kernel/hostname to set it
# don't forget to create this file if you want to give your system a name
if [[ -f /etc/hostname ]]; then
  cat /etc/hostname > /proc/sys/kernel/hostname
else
  echo "mysterious-ikeda" > /proc/sys/kernel/hostname
fi

# mdev is a mini-udev implementation that
# populates /dev with devices by scanning /sys
# see the util-linux/mdev.c file in the busybox source
# for more information
mdev -s
# Maybe this is just depricated since the 4.x series of kernels?
#echo /sbin/mdev > /proc/sys/kernel/hotplug

# the "localhost" loopback network interface is
# down at boot, we have to set it 'up' or we won't be able to
# make local network connections
ip link set up dev lo

# you could add the following to change the keyboard layout at boot
#loadkmap < /usr/share/keymaps/be-latin1.bmap

# mounts all filesystems in /etc/fstab
mount -a
# make the root writable if this hasn't been done already
mount -o remount,rw /

# Enable services (lel)
#ln -s /etc/init.d/syslogd /etc/rc.d
#ln -s /etc/init.d/klogd /etc/rc.d
ln -s /etc/init.d/udhcpc /etc/rc.d

echo "Raising network devices"
OLD="$PWD"
cd /sys/class/net
for dev in $(echo *); do
  if [[ ! "$dev" == "lo" && ! "$dev" == "sit0" ]]; then
    echo "Trying to raise $dev"
    ifup $dev
  fi
done
cd $OLD

# show the fun ascii-art
cat /etc/prelogin